# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(dplyr)
library(ellmer)
library(httr2)
library(magrittr)
library(reactable)
library(rhino)
library(rsconnect)
library(shinycssloaders)
library(treesitter)
library(treesitter.r)
